# Docker Compose configuration for production environment
# Uses pre-built image from Docker registry

services:
  app:
    image: perry2004/perryz.net:latest
    volumes:
      - ${CADDY_CONFIG:-./Caddyfile.prod}:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
    platform: linux/amd64
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "caddy", "version" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
