# Docker Compose configuration for the image scheduler service
# This service runs independently and updates the rolling-images.json file

services:
  scheduler:
    build:
      context: ..
      dockerfile: scheduler/Dockerfile
    volumes:
      # Mount the public/data directory to persist changes
      - ../public/data:/app/public/data
      # Optional: Mount logs directory for easier access
      - ./logs:/var/log
    environment:
      - TZ=UTC
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "test", "-f", "/var/log/fetch-images.log"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # Optional: resource limits
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
