import {
  FaCode,
  FaJava,
  FaPython,
  FaJs,
  FaHtml5,
  FaCss3Alt,
  FaReact,
  FaDatabase,
  FaChartBar,
  FaLanguage,
  FaGithub,
  FaDocker,
  FaAws,
  FaLinux,
  FaCalculator,
  FaRProject,
  FaServer,
  FaMobileAlt,
} from "react-icons/fa";
import {
  SiTypescript,
  SiCplusplus,
  SiC,
  SiMysql,
  SiOracle,
  SiWebgl,
  SiExpress,
  SiTableau,
  SiBlender,
  SiGit,
  SiVim,
  SiGnubash,
  SiJavascript,
  SiBootstrap,
  SiTailwindcss,
  SiSass,
  SiPostgresql,
  SiAnsible,
  SiKubernetes,
  SiGrafana,
  SiTerraform,
  SiNestjs,
  SiMongodb,
  SiGo,
} from "react-icons/si";
import { GiMagnifyingGlass, GiEarthAmerica, GiJapan } from "react-icons/gi";
import { BsDatabaseGear, BsFiletypeSql, BsDiagram3 } from "react-icons/bs";
import { TbMathFunction, TbBrandThreejs, TbMatrix } from "react-icons/tb";
import {
  MdOutlineDataExploration,
  MdOutlineEngineering,
  MdOutlineStorage,
  MdScience,
  MdArchitecture,
} from "react-icons/md";
import { BiTimeFive, BiStats } from "react-icons/bi";
import { IoGameController } from "react-icons/io5";
import { RiEnglishInput } from "react-icons/ri";
import { SkillCategory } from "@/components/pages";

export const skillsData: SkillCategory[] = [
  {
    name: "Programming Languages",
    icon: <FaCode />,
    skills: [
      { name: "TypeScript", icon: <SiTypescript /> },
      { name: "Java", icon: <FaJava /> },
      { name: "Golang", icon: <SiGo /> },
      { name: "JavaScript", icon: <FaJs /> },
      { name: "Python", icon: <FaPython /> },
      { name: "R", icon: <FaRProject /> },
      { name: "C", icon: <SiC /> },
      { name: "C++", icon: <SiCplusplus /> },
      { name: "MATLAB", icon: <MdScience /> },
    ],
  },
  {
    name: "Web Development",
    icon: <FaReact />,
    skills: [
      { name: "HTML 5", icon: <FaHtml5 /> },
      { name: "CSS 3", icon: <FaCss3Alt /> },
      { name: "ECMAScript 6", icon: <SiJavascript /> },
      { name: "TypeScript", icon: <SiTypescript /> },
      { name: "Bootstrap", icon: <SiBootstrap /> },
      { name: "Tailwind CSS", icon: <SiTailwindcss /> },
      { name: "Sass", icon: <SiSass /> },
      { name: "React", icon: <FaReact /> },
      { name: "Responsive Design", icon: <FaMobileAlt /> },
      { name: "WebGL", icon: <SiWebgl /> },
      { name: "Three.js", icon: <TbBrandThreejs /> },
      { name: "Express.js", icon: <SiExpress /> },
      { name: "NestJS", icon: <SiNestjs /> },
      { name: "TanStack", icon: <FaReact /> },
    ],
  },
  {
    name: "Machine Learning & Data Science",
    icon: <MdOutlineDataExploration />,
    skills: [
      { name: "Python", icon: <FaPython /> },
      { name: "R", icon: <FaRProject /> },
      { name: "Statistical Inference", icon: <BiStats /> },
      { name: "Data Preprocessing", icon: <MdOutlineDataExploration /> },
      { name: "Feature Engineering", icon: <MdOutlineEngineering /> },
      { name: "Recommender Systems", icon: <GiMagnifyingGlass /> },
      { name: "Time Series Prediction", icon: <BiTimeFive /> },
      { name: "Interpretation", icon: <MdArchitecture /> },
      { name: "Visualization", icon: <FaChartBar /> },
      { name: "Tableau", icon: <SiTableau /> },
    ],
  },
  {
    name: "AI Development",
    icon: <MdArchitecture />,
    skills: [
      { name: "LangChain", icon: <MdArchitecture /> },
      { name: "LangGraph", icon: <BsDiagram3 /> },
      { name: "Prompt & Context Engineering", icon: <RiEnglishInput /> },
      { name: "AI Agent", icon: <MdArchitecture /> },
      { name: "AI Workflow", icon: <MdOutlineEngineering /> },
      { name: "RAG", icon: <GiMagnifyingGlass /> },
      { name: "Human-in-the-Loop", icon: <FaLanguage /> },
      { name: "ReAct", icon: <BiTimeFive /> },
    ],
  },
  {
    name: "Database Design and Management",
    icon: <FaDatabase />,
    skills: [
      { name: "Relational DB Design", icon: <BsDatabaseGear /> },
      { name: "ER Model", icon: <BsDiagram3 /> },
      { name: "DB Normalization", icon: <BsDatabaseGear /> },
      { name: "Relational Algebra", icon: <BsFiletypeSql /> },
      { name: "SQL", icon: <BsFiletypeSql /> },
      { name: "MySQL DB", icon: <SiMysql /> },
      { name: "OracleDB", icon: <SiOracle /> },
      { name: "PostgreSQL", icon: <SiPostgresql /> },
      { name: "MongoDB", icon: <SiMongodb /> },
      { name: "Data Warehousing", icon: <MdOutlineStorage /> },
    ],
  },
  {
    name: "Math & Statistics",
    icon: <FaCalculator />,
    skills: [
      { name: "Advanced Calculus", icon: <TbMathFunction /> },
      { name: "Linear Algebra", icon: <TbMatrix /> },
      { name: "Statistical Inference", icon: <BiStats /> },
      { name: "Mathematical Proof", icon: <TbMathFunction /> },
      { name: "Probability Theory", icon: <FaCalculator /> },
    ],
  },
  {
    name: "(Human) Languages",
    icon: <FaLanguage />,
    skills: [
      { name: "Chinese - Native", icon: <GiEarthAmerica /> },
      { name: "English - Fluent", icon: <RiEnglishInput /> },
      { name: "Japanese - Beginner", icon: <GiJapan /> },
    ],
  },
  {
    name: "Cloud Computing",
    icon: <FaAws />,
    skills: [
      { name: "AWS", icon: <FaAws /> },
      { name: "Linux", icon: <FaLinux /> },
      { name: "Kubernetes", icon: <SiKubernetes /> },
      { name: "Ansible", icon: <SiAnsible /> },
      { name: "Terraform", icon: <SiTerraform /> },
      { name: "Grafana", icon: <SiGrafana /> },
      { name: "CI/CD", icon: <MdOutlineEngineering /> },
      { name: "GitHub Actions", icon: <FaGithub /> },
      { name: "Golang", icon: <SiGo /> },
      { name: "Distributed System", icon: <FaServer /> },
    ],
  },
  {
    name: "Tools & Technologies",
    icon: <FaGithub />,
    skills: [
      { name: "Git", icon: <SiGit /> },
      { name: "GitHub", icon: <FaGithub /> },
      { name: "Docker", icon: <FaDocker /> },
      { name: "Vim/Nvim", icon: <SiVim /> },
      { name: "Zsh", icon: <SiGnubash /> },
      { name: "Blender", icon: <SiBlender /> },
      {
        name: "Minecraft Plugin & Mod",
        icon: <IoGameController />,
      },
      { name: "MC Server Management", icon: <FaServer /> },
    ],
  },
];
