# Build the lambda function zip file and push to S3
name: Build and Publish Lambda to S3
on:
  push:
    branches:
      - main
    paths:
      - scripts/**
  workflow_dispatch:
jobs:
  push-artifacts-to-s3:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "yarn"
      - name: Build Lambda
        run: |
          cd scripts
          yarn install --frozen-lockfile
          yarn build
          cd dist
          zip -r ../../lambda-function.zip .
          cd ../..
      - name: Deploy to S3
        run: |
          # Upload the Lambda function zip to S3
          aws s3 cp lambda-function.zip s3://${{ secrets.AWS_S3_BUCKET }}/lambda/lambda-function.zip
