# Checks whether the project is buildable on PR creation or updates
name: Build Check on PR
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    paths-ignore:
      - scripts/**
      - .github/workflows/**
      - README.md
  workflow_dispatch:
jobs:
  check-build-success:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build Project
        run: yarn cibuild
