name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Sets permissions of the GITHUB_TOKEN to allow deployment
permissions:
  contents: write
  pages: write
  id-token: write

# Environment settings
env:
  NODE_VERSION: "22"

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for proper versioning

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          echo "Installed dependencies using Yarn"

      - name: Build
        run: |
          echo "Starting build process..."
          yarn build
          echo "🚀 Build completed successfully"

      - name: Copy CNAME file to dist
        run: |
          if [ -f "public/CNAME" ]; then
            cp public/CNAME dist/
            echo "CNAME file copied to dist directory"
          fi

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages # The branch to deploy to
          clean: true # Automatically remove deleted files from the deploy branch
