name: Build and Push All Images to Docker Hub

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Allow only one concurrent deployment
concurrency:
  group: "docker-build"
  cancel-in-progress: true

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: read

# Environment settings
env:
  NODE_VERSION: "22"
  MAIN_IMAGE: "perry2004/perryz.net"
  SCHEDULER_IMAGE: "perry2004/perryz.net-scheduler"

jobs:
  build-and-push-main:
    name: Build and Push Main App Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for proper versioning

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for main app
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.MAIN_IMAGE }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Main Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=main
          cache-to: type=gha,mode=max,scope=main

  build-and-push-scheduler:
    name: Build and Push Scheduler Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for proper versioning

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for scheduler
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.SCHEDULER_IMAGE }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Scheduler Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./scheduler/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=scheduler
          cache-to: type=gha,mode=max,scope=scheduler
